sudo: required
service:
  - docker

before_install:
  - docker build -t alejandrocampana/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true alejandrocampana/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-743724042425"
  bucket_path: "docker"
  on:
    brach: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

